### ISSUE TITLE
Wand of Negation

### ISSUE THREAD

**Issue by Kaelthanas** [LolnetModPack/Regrowth#1]
Hi Speaking for Devco's Community as an Admin, We've recently become aware of the Millenaire mod, and it's rampant growth so to speak. I see that you've made a recipe for the villager wand, But not the wand of negation. I've tried make a mine tweaker recipe for it as we are allowing our members to remove the village themselves since we've warned them of millenairs bypass of world guard/claims

**Comment by 0zlw** [comment]
https://github.com/thephoenixlodge/Regrowth-Stuff/issues
